theme: jekyll-theme-minimal
title: RomiBot - Termos e Condições do Serviço.
description: Os termos e condições acerca do bot de WhatsApp. RomiBot, criada por Sergio Ruiz, licenciando em informática educacional na Universidade Federal do Oeste do Pará.
